FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/Shared/*.csproj Shared/Shared/
COPY Services/PhotoStock/PhotoStock/*.csproj Services/PhotoStock/PhotoStock/
RUN dotnet restore Services/PhotoStock/PhotoStock/*.csproj
COPY . .
RUN dotnet publish Services/PhotoStock/PhotoStock/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","PhotoStock.dll" ]